### ISSUE TITLE
Roles not visible

### ISSUE THREAD

**Issue by wvdvegt** [gorco/gf#32]
When i log in and look at my profile, no roles are shown

In the console i see the following error:

HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(XHR): GET - http://145.20.132.23:3000/api/roles

**Comment by RotaruDan** [comment]
Hello,

I'm guessing (from this issue https://github.com/e-ucm/rage-analytics-frontend/issues/33) that you've signed up from the A2 admin page `http://145.20.132.23:3000/signup` which doesn't automatically assign any role to the registered user. So when you try to see your own roles you won't be able to se any role at all.

Try signing up from the analytics-frontend signup page: `http://145.20.132.23:3000/api/proxy/afront/signup`. This should work just as before.

There are two different LogIn endpoints:
- A2 frontend (for Administration, e.g. accessing as root/root):
  `http://145.20.132.23:3000/signup`
- Analytics-frontend (for Analytics, e.g. accessing as a Developer/Teacher)
  `http://145.20.132.23:3000/api/proxy/afront/signup`

Best regards,
 Dan.

**Comment by wvdvegt** [comment]
Thanks that did the trick. We dit not put nginx in front yet in order to see wether everything was working as before.

**Comment by wvdvegt** [comment]
Hi 

It's not about logging in as the other ticket but about the profile page. The bottom section where the roles should be listed is empty (and i see an error in the javascript console)

**Comment by gorco** [comment]
If you have a role, you will see something like the following image

![teacher](https://cloud.githubusercontent.com/assets/5657407/13179780/c3e8b9a6-d725-11e5-8eaf-a523004daf21.png)

The 403 error is because only the admin role can see the resources and permissions. So the request of `GET /api/roles` and `GET /api/roles/teacher` throw this error.

If you don't see any role name is because your user don't have a role (this happens when you SignUp from the A2 administration frontend).

If you log in as admin (root/root) you'll see the full information:

![roles](https://cloud.githubusercontent.com/assets/5657407/13179810/f5175460-d725-11e5-86be-b644be3e63e7.png)

**Comment by wvdvegt** [comment]
My comment was not about not being able to see roles as a student, but that the roles header for the listing is visible and the page tries to retrieve them which leads to an error. 

This kind of errors tends obscure other ones (or distract the programmer) when debugging so should be avoided.

**Comment by gorco** [comment]
True, we should avoid this errors, we'll romeve it, but for now it's usefull for debugging purposes.
